=== kadarbalint/OYDQP1xmlGyak/XMLFeladatOYDQP1/XMLSchemaOydqp1.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="mikulaslogisztikaihivatal">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="kozpontok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="kozpont" type="kozpont" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="pilotak">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pilota" type="pilota" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="jarmuvek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="jarmu" type="jarmu" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="ajandekok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ajandek" type="ajandek" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="gyermekek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="gyermek" type="gyermek" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="gyermekerdeklodesek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="gyermekerdeklodes" type="gyermekerdeklodes" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="ajandek-gyermek_kapcsolo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="kapcsolo" type="ajandek-gyermek" minOccurs="0" maxOccurs="unbounded"  />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      
      </xs:sequence>
    </xs:complexType>


	<!-- key - keyref restrictions -->

        <xs:key name="kozpontid">
            <xs:selector xpath=".//kozpont" />
            <xs:field xpath="@id" />
        </xs:key>
        
        <xs:keyref name="kozpontidref2" refer="kozpontid">
        	<xs:selector xpath=".//ajandek"/>
        	<xs:field xpath="@kozpontid"/>
        </xs:keyref>
        
        <xs:keyref name="kozpontidref3" refer="kozpontid">
        	<xs:selector xpath=".//jarmu"/>
        	<xs:field xpath="@kozpontid"/>
        </xs:keyref>
       

        <xs:key name="pilotaid">
            <xs:selector xpath=".//pilota" />
            <xs:field xpath="@id" />
        </xs:key>
        

        <xs:key name="jarmuid">
            <xs:selector xpath=".//jarmu" />
            <xs:field xpath="@id" />
        </xs:key>

        <xs:key name="ajandekid">
            <xs:selector xpath=".//ajandek" />
            <xs:field xpath="@id" />
        </xs:key>
        <xs:keyref name="ajandekidref" refer="ajandekid">
        <xs:selector xpath=".//kapcsolo"/>
        <xs:field xpath="@ajandekID"/>
        </xs:keyref>
        

        <xs:key name="gyermekid">
            <xs:selector xpath=".//gyermek" />
            <xs:field xpath="@id" />
        </xs:key>
        <xs:keyref name="gyermekidref1" refer="gyermekid">
            <xs:selector xpath=".//kapcsolo" />
            <xs:field xpath="@gyermekID" />
        </xs:keyref>
        <xs:keyref name="gyermekidref2" refer="gyermekid">
            <xs:selector xpath=".//gyermekerdeklodes" />
            <xs:field xpath="@gyermekid" />
        </xs:keyref>
        
        
        <xs:key name="gyermekerdeklodesid">
            <xs:selector xpath=".//gyermekerdeklodes" />
            <xs:field xpath="@id" />
        </xs:key>
        
        
        
    </xs:element>
	

                                                      

<xs:complexType name="kozpont">
    <xs:sequence>
      <xs:element name="szankokszama" type="xs:int" />
        <xs:element name="lokacio" type="xs:string" />
        <xs:element name="elerheto_e" type="xs:byte" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="pilota">
    <xs:sequence>
        <xs:element name="nev" type="xs:string" />
        <xs:element name="repultido" type="xs:int" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="jarmu">
    <xs:sequence>
        <xs:element name="futasteljesitmeny" type="xs:int" />
        <xs:element name="uzemanyagszint" type="xs:int" />
        <xs:element name="tankolni_kell" type="xs:byte" />
        <xs:element name="evjarat" type="xs:int" />
        <xs:element name="terhelhetoseg" type="xs:int" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required" />
    <xs:attribute name="kozpontid" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="ajandek">
    <xs:sequence>
        <xs:element name="nev" type="xs:string" />
        <xs:element name="kategoria" type="xs:string" />
        <xs:element name="suly" type="xs:int" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required" />
    <xs:attribute name="kozpontid" type="xs:int" use="required" />

</xs:complexType>

<xs:complexType name="gyermek">
    <xs:sequence>
        <xs:element name="nev" type="xs:string" />
        <xs:element name="koordinata" type="koordinata" />
        <xs:element name="virgacs_kell" type="xs:byte" />
        <xs:element name="fiu_e" type="xs:byte" />
        <xs:element name="kor" type="xs:int" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="gyermekerdeklodes">
    <xs:sequence>
        <xs:element name="kivansag" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required" />
    <xs:attribute name="gyermekid" type="xs:int" use="required" />

</xs:complexType>

<xs:complexType name="ajandek-gyermek">
    <xs:attribute name="ajandekID" type="xs:int" use="required" />
    <xs:attribute name="gyermekID" type="xs:int" use="required" />
</xs:complexType>

<xs:complexType name="koordinata">
  <xs:sequence>
      <xs:element name="north" >
      <xs:simpleType>
              <xs:restriction base="xs:int">
                  <xs:minInclusive value="0"></xs:minInclusive>
                  <xs:maxExclusive value="9999"></xs:maxExclusive>
              </xs:restriction>
          </xs:simpleType>
       </xs:element>
      <xs:element name="west">
      <xs:simpleType>
              <xs:restriction base="xs:int">
                <xs:minInclusive value="0"></xs:minInclusive>
                <xs:maxExclusive value="9999"></xs:maxExclusive>
              </xs:restriction>
          </xs:simpleType>
      </xs:element>
  </xs:sequence>
</xs:complexType>


</xs:schema>

=== kadarbalint/OYDQP1xmlGyak/XMLFeladatOYDQP1/XMLOydqp1.xml
<?xml version="1.0" encoding="UTF-8"?>
<mikulaslogisztikaihivatal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaOydqp1.xsd">
<kozpontok>
    
    <kozpont id ="1111">
        <szankokszama>1</szankokszama>
        <lokacio>Rénszarvasistálló</lokacio>
         <elerheto_e>1</elerheto_e>
    </kozpont>
    <kozpont id = "1222">
        <szankokszama>3</szankokszama>
        <lokacio>Mézeskalácsudvar</lokacio>
         <elerheto_e>1</elerheto_e>
    </kozpont>
    <kozpont id ="1333">
        <szankokszama>4</szankokszama>
        <lokacio>Gumicukorműhely</lokacio>
         <elerheto_e>1</elerheto_e>
    </kozpont>
    <kozpont id ="1444">
        <szankokszama>2</szankokszama>
        <lokacio>Virgácsfa</lokacio>
         <elerheto_e>0</elerheto_e>
    </kozpont>
    <kozpont id ="1555">
        <szankokszama>1</szankokszama>
        <lokacio>Gyümölcsudvar</lokacio>
         <elerheto_e>1</elerheto_e>
    </kozpont>
</kozpontok>

<pilotak>
    <pilota id ="0">
        <nev>Télapó</nev>
        <repultido>302</repultido>
    </pilota>

     <pilota id ="1">
        <nev>Télapó</nev>
        <repultido>302</repultido>
     </pilota>

    <pilota id ="2">
        <nev>Télapó</nev>
        <repultido>302</repultido>
     </pilota>

    <pilota id ="3">
        <nev>Télapó</nev>
         <repultido>302</repultido>
    </pilota>

    <pilota id ="4">
        <nev>Télapó</nev>
         <repultido>302</repultido>
    </pilota>

    <pilota id ="5">
        <nev>Télapó</nev>
         <repultido>302</repultido>
    </pilota>
</pilotak>


<jarmuvek>
    <jarmu id="3000" kozpontid="1111">
       
        <futasteljesitmeny>1128111</futasteljesitmeny>
        <uzemanyagszint>70</uzemanyagszint>
        <tankolni_kell> 1</tankolni_kell>
        <evjarat>1999</evjarat>
        <terhelhetoseg>1000</terhelhetoseg>
    </jarmu>

    <jarmu id="3001" kozpontid="1222">
        <futasteljesitmeny>345254</futasteljesitmeny>
        <uzemanyagszint>25</uzemanyagszint>
        <tankolni_kell> 1</tankolni_kell> 
        <evjarat>1987</evjarat>
        <terhelhetoseg>1000</terhelhetoseg>
    </jarmu>

    <jarmu id="3002" kozpontid="1333">
        <futasteljesitmeny>634524</futasteljesitmeny>
        <uzemanyagszint>13</uzemanyagszint>
        <tankolni_kell>1</tankolni_kell>
         <evjarat>1968</evjarat>
        <terhelhetoseg>1000</terhelhetoseg>
    </jarmu>

    <jarmu id="3003" kozpontid="1444">
        <futasteljesitmeny>156158</futasteljesitmeny>
        <uzemanyagszint>100</uzemanyagszint>
        <tankolni_kell> 1</tankolni_kell>
        <evjarat>1975</evjarat>
        <terhelhetoseg>1000</terhelhetoseg>
    </jarmu>

    <jarmu id="3004" kozpontid="1555">
        <futasteljesitmeny>784185</futasteljesitmeny>
        <uzemanyagszint>90 </uzemanyagszint>
        <tankolni_kell> 1</tankolni_kell>
        <evjarat>1981</evjarat>
        <terhelhetoseg>1000</terhelhetoseg>
    </jarmu>
</jarmuvek>
<ajandekok>
    <ajandek id="1345" kozpontid="1111">
        <nev>Lego Kastély</nev>
        <kategoria>Lego</kategoria>
        <suly>13</suly>
    </ajandek>

    <ajandek id="1365" kozpontid ="1111">
        <nev>Lego Barbie</nev>
        <kategoria>Lego</kategoria>
        <suly>18</suly>
       
    </ajandek>

    <ajandek id="1745" kozpontid = "1555">
        <nev>Baseball Ütő</nev>
        <kategoria>Sport</kategoria>
        <suly>83</suly>
    </ajandek>

    <ajandek id="1385" kozpontid="1555">
        <nev>Golfütő</nev>
        <kategoria>Sport</kategoria>
        <suly>90</suly>
    </ajandek>

    <ajandek id="3345" kozpontid ="1444">
        <nev>Xbox One</nev>
        <kategoria>Xbox</kategoria>
        <suly>30</suly>
    </ajandek>
</ajandekok>
<gyermekek>
    <gyermek id="9999">
        <nev>Kádár Bálint</nev>
        <koordinata>
            <north>9000</north>
            <west>2300</west>
        </koordinata>
       
        <virgacs_kell>0</virgacs_kell>
        <fiu_e>1</fiu_e>
        <kor>21</kor>
    </gyermek>

    <gyermek id="9998">
        <nev>Kiss Balázs</nev>
        <koordinata>
            <north>8500</north>
            <west>2300</west>
        </koordinata>
      
        <virgacs_kell>1</virgacs_kell>
        <fiu_e>1</fiu_e>
        <kor>5</kor>
    </gyermek>

    <gyermek id="9997">
        <nev>Kovács Nóri</nev>
        <koordinata>
        <north>9000</north>
        <west>1600</west>
        </koordinata>
        
        <virgacs_kell>1</virgacs_kell>
        <fiu_e>0</fiu_e>
        <kor>28</kor>
    </gyermek>

    <gyermek id="9996">
        <nev>Tóth Anna</nev>
        <koordinata>
        <north>6300</north>
        <west>2800</west>
        </koordinata>
        <virgacs_kell>1</virgacs_kell>
        <fiu_e>0</fiu_e>
        <kor>26</kor>
    </gyermek>

    <gyermek id="9995">
        <nev>Lenkei Márk</nev>
        <koordinata>
        <north>9000</north>
        <west>2300</west>
        </koordinata>
        <virgacs_kell>1</virgacs_kell>
        <fiu_e>1</fiu_e>
        <kor>21</kor>
    </gyermek>
</gyermekek>
<gyermekerdeklodesek>
    <gyermekerdeklodes id="00" gyermekid="9999">
        <kivansag>"Autók"</kivansag>
    </gyermekerdeklodes>

    <gyermekerdeklodes id="01" gyermekid ="9997">
        <kivansag>"Babák"</kivansag>
    </gyermekerdeklodes>

    <gyermekerdeklodes id="02" gyermekid="9999">
        <kivansag>"Lego"</kivansag>
    </gyermekerdeklodes>
    
    <gyermekerdeklodes id="03" gyermekid="9995">
        <kivansag>"Sport"</kivansag>
    </gyermekerdeklodes>

    <gyermekerdeklodes id="04" gyermekid ="9999">
        <kivansag>"Xbox"</kivansag>
    </gyermekerdeklodes>
</gyermekerdeklodesek>
<ajandek-gyermek_kapcsolo>
    <kapcsolo ajandekID="1345" gyermekID="9999" /> 
    <kapcsolo ajandekID="1385" gyermekID="9999" /> 
    <kapcsolo ajandekID="1745" gyermekID="9999" /> 
    <kapcsolo ajandekID="3345" gyermekID="9999" /> 
    <kapcsolo ajandekID="1365" gyermekID="9997" /> 
    <kapcsolo ajandekID="1365" gyermekID="9996" /> 
    <kapcsolo ajandekID="1385" gyermekID="9998" /> 
    <kapcsolo ajandekID="3345" gyermekID="9995" /> 
</ajandek-gyermek_kapcsolo>


</mikulaslogisztikaihivatal>
